Update autom_2_wms.yml

diff --git a/.github/workflows/autom_2_wms.yml b/.github/workflows/autom_2_wms.yml
--- a/.github/workflows/autom_2_wms.yml
+++ b/.github/workflows/autom_2_wms.yml
@@ -2,7 +2,7 @@ name: cron schedule WMS
 on:
  push:
     branches:
-      - b
+      - develop_autom
  
 
 jobs:
@@ -28,6 +28,7 @@ jobs:
       
       - name: WMS Automation module-1
         run: |
+         mvn compile
          mvn install test -DsuiteXmlFile='CountingTestNGRunner.xml'
         working-directory: AFS_Automation/WMS_Automation 
         
@@ -37,79 +38,79 @@ jobs:
       
         
 # ##########################################################################        
-  job2:  
-    needs: job1
-    name : job2 name
-    if: success() || failure()
-    runs-on: self-hosted
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v3
-      - uses: actions/checkout@v3
-      - uses: actions/setup-java@v3
-        with:
-           distribution: temurin
-           java-version: '16'
-           cache: maven
-           -name: Build with Maven
-           run: mvn -B package --file pom.xml
+#   job2:  
+#     needs: job1
+#     name : job2 name
+#     if: success() || failure()
+#     runs-on: self-hosted
+#     steps:
+#       - name: Checkout source code
+#         uses: actions/checkout@v3
+#       - uses: actions/checkout@v3
+#       - uses: actions/setup-java@v3
+#         with:
+#            distribution: temurin
+#            java-version: '16'
+#            cache: maven
+#            -name: Build with Maven
+#            run: mvn -B package --file pom.xml
      
-      - name: WMS Automation module-2
-        run: |
-         mvn install test -DsuiteXmlFile='LoginTestNGRunner.xml'
-        working-directory: AFS_Automation/WMS_Automation 
+#       - name: WMS Automation module-2
+#         run: |
+#          mvn install test -DsuiteXmlFile='LoginTestNGRunner.xml'
+#         working-directory: AFS_Automation/WMS_Automation 
         
        
         
       
      
         
-# ###########################################################################        
-  job3:  
-    needs: job2
-    name : job3 name
-    if: success() || failure()
-    runs-on: self-hosted
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v3
-      - uses: actions/checkout@v3
-      - uses: actions/setup-java@v3
-        with:
-           distribution: temurin
-           java-version: '16'
-           cache: maven
-           -name: Build with Maven
-           run: mvn -B package --file pom.xml
+# # ###########################################################################        
+#   job3:  
+#     needs: job2
+#     name : job3 name
+#     if: success() || failure()
+#     runs-on: self-hosted
+#     steps:
+#       - name: Checkout source code
+#         uses: actions/checkout@v3
+#       - uses: actions/checkout@v3
+#       - uses: actions/setup-java@v3
+#         with:
+#            distribution: temurin
+#            java-version: '16'
+#            cache: maven
+#            -name: Build with Maven
+#            run: mvn -B package --file pom.xml
    
-      - name: WMS Automation module-3
-        run: |
-         mvn install test -DsuiteXmlFile='LookupTestNGRunner.xml'
-        working-directory: AFS_Automation/WMS_Automation 
+#       - name: WMS Automation module-3
+#         run: |
+#          mvn install test -DsuiteXmlFile='LookupTestNGRunner.xml'
+#         working-directory: AFS_Automation/WMS_Automation 
         
        
         
       
               
-              # ###########################################################################        
-  job4:  
-    needs: job3
-    name : job4 name
-    if: success() || failure()
-    runs-on: self-hosted
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v3
-      - uses: actions/checkout@v3
-      - uses: actions/setup-java@v3
-        with:
-           distribution: temurin
-           java-version: '16'
-           cache: maven
-           -name: Build with Maven
-           run: mvn -B package --file pom.xml
+#               # ###########################################################################        
+#   job4:  
+#     needs: job3
+#     name : job4 name
+#     if: success() || failure()
+#     runs-on: self-hosted
+#     steps:
+#       - name: Checkout source code
+#         uses: actions/checkout@v3
+#       - uses: actions/checkout@v3
+#       - uses: actions/setup-java@v3
+#         with:
+#            distribution: temurin
+#            java-version: '16'
+#            cache: maven
+#            -name: Build with Maven
+#            run: mvn -B package --file pom.xml
    
-      - name: WMS Automation module-4
-        run: |
-         mvn install test -DsuiteXmlFile='WorkQueueTestNGRunner.xml'
-        working-directory: AFS_Automation/WMS_Automation
+#       - name: WMS Automation module-4
+#         run: |
+#          mvn install test -DsuiteXmlFile='WorkQueueTestNGRunner.xml'
+#         working-directory: AFS_Automation/WMS_Automation
